apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nginx-static-secret
spec:
  encryptedData:
    CDN_ORIGIN_HEADER_VALUE: AgDDykv6o82KkEvxPRg5OGmcefnMSsRYz/l2hcKtd7wK0XB/MAE5J0Fkc2VtTvEuy0AkogYbRUNYifT2OJjZITkebUuBIQts7dBerd/D1bnUavX2NunIxr2nv0S+dW0OvyttTQxLO5yZYJ3iC+eyqzYAp7SYFA0SkkKw8x4cdbm5R/ZsUqt5LRv+RTdvm4zyIayLVDnRi6b5mPy/SNjdqDrD3hA86qxBdVI1k2omK5DmmjPhuEgX68oTxBp4xo3sxlhd8phAMHIWnORVnYzgKYsIhAX5qaXL5jXkvdq3lrSgD+ZfGDc6Gs36IRaJ7RY9sw/dif1xzx4MfS1x5ecvNC15SGywcPdgy2+FmnsAeXLgpDGCyykStctHvagrSKVa5xOCQ5o9J+GFbCaxW49nFbOzYeAQ2QGz4Njbf0of+HGnfcA9mCXb9yNd0Zi6pSyjN3yPPeuaeceFuAP1rvNAEFrrQvStZ/AD+5ZPbSka9l0YoWZEWnkh2ER/0d4UMI+Vo0+y/usoMr4CBtRziir/HG30dZXoVN6bbEb3tN5qOLDZ1gZfRIoaTCqV1uuo3Xd5rU2KZ4bq3fCsOSmYhjFIMd4i/fe/VvaN02g9QMTI/d5uhbw3NCvxrPZ8g1fsJHx5Ux1lUSoAj8m2OLpqS+t5lDJ2h0nzP9UtM0BlLMkCgobCTOVuY6ntPQru+4l1fCTMRKPi7qxUl0shp5I3U34YdujQC3+MpVGJhuntzuytKOXePA==
  template:
    metadata:
      creationTimestamp: null
      name: nginx-static-secret
