# This workflow deploys to production on any push to main
name: Publish to production

on:
  push:
    branches: ["main"]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      contents: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm i -g pm2
          npm i dotenv

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Hash known_hosts
        run: ssh-keygen -Hf ~/.ssh/known_hosts

      # Omitting output for security
      - name: Deploy to production
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: pm2 deploy production > /dev/null
